#! /usr/bin/perl

# Craig Tanis
# Tulane University
# Electrical Engineering and Computer Science

# byte-them
# Sun Feb 15 23:18:49 1998
# make sure all elc files in current directory are up-to-date
# skip compilation of those files mentioned in .dont-compile

my $file;
my @filelist=();


for $file (glob("*.el")) {
    if (-e $file."c") {
	my $f1= -M $file;
	my $f2= -M $file."c" or 0;
	if ( $f1 < $f2) {
#	    print "$file\n";
	    push (@filelist, $file);
	}
    } else {
#	print "$file\n";
	push (@filelist, $file);
    }
}

# now get the filenames not to compile
open(NOT,".dont-compile") or warn "No .dont-compile file\n";
my @names=<NOT>;

foreach $f (@filelist) {
    push @files,$f
	unless grep /$f/,@names;
}

# what's a better way to ensure that the load path used in batch mode
# contain the current directory than to hardcode in 'add-current-dir'?

`emacs -batch -f batch-byte-compile @files`;

print "elisp up-to-date\n";
